export const RumMeasureTypes = {
    CLUSTER_PARAMS: 'CLUSTER_PARAMS',

    ACCOUNTS: 'ACCOUNTS_',

    NAVIGATION_PRELOAD: 'NAVIGATION_PRELOAD',

    NAVIGATION_CONTENT_DOCUMENT: 'NAVIGATION_CONTENT_DOCUMENT',
    NAVIGATION_CONTENT_FILE: 'NAVIGATION_CONTENT_FILE',
    NAVIGATION_CONTENT_LINK: 'NAVIGATION_CONTENT_LINK',
    NAVIGATION_CONTENT_MAP_NODE: 'NAVIGATION_CONTENT_MAP_NODE_',
    NAVIGATION_CONTENT_REPLICATED_TABLE: 'NAVIGATION_CONTENT_REPLICATED_TABLE',
    NAVIGATION_CONTENT_TABLE_STATIC: 'NAVIGATION_CONTENT_TABLE_STATIC',
    NAVIGATION_CONTENT_TABLE_DYNAMIC: 'NAVIGATION_CONTENT_TABLE_DYNAMIC',
    NAVIGATION_CONTENT_TRANSACTION: 'NAVIGATION_CONTENT_TRANSACTION',
    NAVIGATION_CONTENT_TRANSACTION_MAP: 'NAVIGATION_CONTENT_TRANSACTION_MAP',

    NAVIGATION_TAB_ACL: 'NAVIGATION_TAB_ACL',
    NAVIGATION_TAB_ACL_ACCESS: 'NAVIGATION_TAB_ACL_ACCESS',
    NAVIGATION_TAB_ANNOTATION: 'NAVIGATION_TAB_ANNOTATION',
    NAVIGATION_TAB_ATTRIBUTES: 'NAVIGATION_TAB_ATTRIBUTES',
    NAVIGATION_TAB_USER_ATTRIBUTES: 'NAVIGATION_TAB_USER_ATTRIBUTES',
    NAVIGATION_TAB_LOCKS: 'NAVIGATION_TAB_LOCKS',
    NAVIGATION_TAB_SCHEMA: 'NAVIGATION_TAB_SCHEMA',
    NAVIGATION_TAB_TABLETS: 'NAVIGATION_TAB_TABLETS',
    NAVIGATION_TAB_TABLET_ERRORS: 'NAVIGATION_TAB_TABLET_ERRORS',

    OPERATIONS_LIST: 'OPERATIONS_LIST_',

    OPERATION: 'OPERATION',
    OPERATION_TAB_DETAILS: 'OPERATION_TAB_DETAILS',
    OPERATION_TAB_ATTRIBUTES: 'OPERATION_TAB_ATTRIBUTES',
    OPERATION_TAB_SPECIFICATION: 'OPERATION_TAB_SPECIFICATION',
    OPERATION_TAB_STATISTICS: 'OPERATION_TAB_STATISTICS',
    OPERATION_TAB_MONITOR: 'OPERATION_TAB_MONITOR',
    OPERATION_TAB_PARTITION_SIZES: 'OPERATION_TAB_PARTITION_SIZES',
    OPERATION_TAB_JOB_SIZES: 'OPERATION_TAB_JOB_SIZES',
    OPERATION_TAB_JOBS: 'OPERATION_TAB_JOBS',

    SCHEDULING: 'SCHEDULING_',
    SCHEDULING_OVERVIEW: 'SCHEDULING_OVERVIEW',
    SCHEDULING_DETAILS: 'SCHEDULING_DETAILS',
    SCHEDULING_MONITOR: 'SCHEDULING_MONITOR',
    SCHEDULING_ACL: 'SCHEDULING_ACL',

    YQL_KIT_WIDGET: 'YQL_KIT_WIDGET',
} as const;
