ui:
  replicaCount: 1
  image:
    repository: ytsaurus/ui
    pullPolicy: IfNotPresent
    tag: ""

  clusterConfig:
    clusters: []
      # - authentication: basic
      #   description: My first YTsaurus. Handle with care.
      #   environment: testing
      #   group: My YTsaurus clusters
      #   id: minisaurus
      #   name: minisaurus
      #   primaryMaster:
      #     cellTag: 1
      #   proxy: http-proxies-lb.testing.svc.cluster.local
      #   secure: false
      #   theme: lavander

  env:
    - name: ALLOW_PASSWORD_AUTH
      value: "1"

  secrets:
    interfaceSecrets:
      # see https://github.com/ytsaurus/ytsaurus-ui/tree/main/packages/ui#how-to-work-with-the-repo
      secretName: "yt-ui-secret"
      secretKey: "yt-interface-secret.json"

service:
  type: NodePort
  port: 80

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

ngnix:
  useCustomConfig: false
  # name of config map where custom config for nginx is located 
  configMapName: "custom-nginx-configmap"
  configMapkey: "ngnix.conf"

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""


settings:
  odinBaseUrl: ""
  directDownload: true
  
securityContext: {}

resources: {}

nodeSelector: {}
