export const PROMETHEUS_DASHBOARD_TYPES = [
    'account',
    'bundle-ui-user-load',
    'bundle-ui-resource',
    'bundle-ui-cpu',
    'bundle-ui-memory',
    'bundle-ui-disk',
    'bundle-ui-lsm',
    'bundle-ui-network',
    'bundle-ui-efficiency',
    'bundle-ui-rpc-proxy-overview',
    'bundle-ui-rpc-proxy',
    'chyt-monitoring',
    'cluster-resources',
    'flow-general',
    'job',
    'master-global',
    'master-local',
    'operation',
    'queue-metrics',
    'queue-consumer-metrics',
    'scheduler-internal',
    'scheduler-pool',
] as const;

export type PrometheusDashboardType = (typeof PROMETHEUS_DASHBOARD_TYPES)[number];
