export const LOAD_JOB_DATA_REQUEST = 'JOB:GENERAL:LOAD_JOB_DATA_REQUEST';
export const LOAD_JOB_DATA_SUCCESS = 'JOB:GENERAL:LOAD_JOB_DATA_SUCCESS';
export const LOAD_JOB_DATA_FAILURE = 'JOB:GENERAL:LOAD_JOB_DATA_FAILURE';
export const LOAD_JOB_DATA_CANCELLED = 'JOB:GENERAL:LOAD_JOB_DATA_CANCELLED';

export const LOAD_JOB_COMPETITORS_REQUEST = 'JOB:GENERAL:LOAD_JOB_COMPETITORS_REQUEST';
export const LOAD_JOB_COMPETITORS_SUCCESS = 'JOB:GENERAL:LOAD_JOB_COMPETITORS_SUCCESS';
export const LOAD_JOB_COMPETITORS_FAILURE = 'JOB:GENERAL:LOAD_JOB_COMPETITORS_FAILURE';
export const LOAD_JOB_COMPETITORS_CANCELLED = 'JOB:GENERAL:LOAD_JOB_COMPETITORS_CANCELLED';

export const LOAD_JOB_SPECIFICATION_REQUEST = 'JOB:GENERAL:LOAD_JOB_SPECIFICATION_REQUEST';
export const LOAD_JOB_SPECIFICATION_SUCCESS = 'JOB:GENERAL:LOAD_JOB_SPECIFICATION_SUCCESS';
export const LOAD_JOB_SPECIFICATION_FAILURE = 'JOB:GENERAL:LOAD_JOB_SPECIFICATION_FAILURE';
export const LOAD_JOB_SPECIFICATION_CANCELLED = 'JOB:GENERAL:LOAD_JOB_SPECIFICATION_CANCELLED';

export const COLLAPSE_TABLE = 'JOB:STATISTICS:COLLAPSE_TABLE';
export const EXPAND_TABLE = 'JOB:STATISTICS:EXPAND_TABLE';
export const CHANGE_FILTER = 'JOB:STATISTICS:CHANGE_FILTER';
export const MIX_TABLE = 'JOB:STATISTICS:MIX_TABLE';

export const CHANGE_OMIT_NODE_DIRECTORY = 'JOB:SPECIFICATION:CHANGE_OMIT_NODE_DIRECTORY';
export const CHANGE_OMIT_INPUT_TABLES_SPECS = 'JOB:SPECIFICATION:CHANGE_OMIT_INPUT_TABLES_SPECS';
export const CHANGE_OMIT_OUTPUT_TABLES_SPECS = 'JOB:SPECIFICATION:CHANGE_OMIT_OUTPUT_TABLES_SPECS';

export const Tab = {
    DETAILS: 'details',
    ATTRIBUTES: 'attributes',
    STATISTICS: 'statistics',
    SPECIFICATION: 'specification',
};

export const DEFAULT_TAB = Tab.DETAILS;
export const TREE_ROOT_NAME = '<Root>';

// eslint-disable-next-line @typescript-eslint/naming-convention
export enum TREE_STATE {
    EXPANDED = 'expanded',
    COLLAPSED = 'collapsed',
    MIXED = 'mixed',
}
