export const SUGGEST_TABLET_CELL_BUNDLES_REQUEST = 'SUGGEST_TABLET_CELL_BUNDLES_REQUEST';
export const SUGGEST_TABLET_CELL_BUNDLES_SUCCESS = 'SUGGEST_TABLET_CELL_BUNDLES_SUCCESS';
export const SUGGEST_TABLET_CELL_BUNDLES_ERROR = 'SUGGEST_TABLET_CELL_BUNDLES_ERROR';
