apiVersion: v1
kind: Service
metadata:
  name: {{ include "ytsaurus-ui-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ytsaurus-ui-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "ytsaurus-ui-chart.selectorLabels" . | nindent 4 }}
