name: "[ci]: Docker cache"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ci-docker-cache.yaml
      - packages/ui/Dockerfile
      - packages/ui/package.json
      - packages/ui/package-lock.json

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Warm main Docker cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        with:
          version: latest
      - name: Build UI
        uses: docker/build-push-action@v7
        with:
          context: packages/ui
          cache-from: type=gha,version=2,scope=ui-main
          cache-to: type=gha,version=2,scope=ui-main,mode=max
