name: CI

on:
  pull_request:

jobs:
  verify_files:
    name: Lint & Unit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
          cache: "npm"
      - name: Install Packages
        run: npm ci
      - name: Lint Files
        run: npm run lint
      - name: Unit Tests
        run: npm run test
