name: "[ci]: Statoscope"

on:
  pull_request:

jobs:
  verify_files:
    name: Statoscope
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
      - name: Install Packages
        run: npm ci
      - name: Analyze build
        run: |
          cd packages/ui
          npm run build:analyze
          mv dist/public/build/stats.json .
          cp statoscope.config.js statoscope.config.js.bak
      - name: Analyze previos build
        run: |
          cd packages/ui
          git reset --hard ${{ github.event.pull_request.base.sha }}
          npm ci
          npm run build:analyze
          mv dist/public/build/stats.json ./prev-stats.json
      - name: Validate
        run: |
          cd packages/ui
          cp statoscope.config.js.bak statoscope.config.js
          npx statoscope validate -i ./stats.json -r ./prev-stats.json
